package insight

import (
	"errors"
	"fmt"
	"time"

	"github.com/hunterkilltree/vn-stock-sim/backend/internal/market"
	"github.com/hunterkilltree/vn-stock-sim/backend/internal/symbol"
)

var ErrSymbolNotFound = errors.New("symbol not found")

const sixMonthsSeconds = 180 * 24 * 60 * 60
const smaPeriod = 20

type SymbolPort interface {
	Detail(sym string) (symbol.Detail, bool)
}

type MarketPort interface {
	GetBars(sym, resolution string, from, to int64) []market.Bar
	GetIndicator(sym, resolution, indicator string, period int, from, to int64) []market.IndicatorPoint
}

// Service generates a deterministic, rule-based "insight" from data the
// backend already has (price/fundamentals + bars + SMA) -- not an LLM
// call. See types.go's Insight.Source and RESUME.md for why: a real
// model needs an API key and has a real per-call cost, which is a
// decision for the user to make explicitly, not something to wire up
// silently. The rules here are intentionally simple and inspectable.
type Service struct {
	symbols SymbolPort
	market  MarketPort
}

func NewService(symbols SymbolPort, market MarketPort) *Service {
	return &Service{symbols: symbols, market: market}
}

func (s *Service) Generate(sym string) (Insight, error) {
	detail, ok := s.symbols.Detail(sym)
	if !ok {
		return Insight{}, ErrSymbolNotFound
	}

	now := time.Now()
	to := now.Unix()
	from := to - sixMonthsSeconds
	bars := s.market.GetBars(detail.Symbol.Symbol, "1D", from, to)
	sma := s.market.GetIndicator(detail.Symbol.Symbol, "1D", "sma", smaPeriod, from, to)

	signals := buildSignals(detail, bars, sma)
	return Insight{
		Symbol:      detail.Symbol.Symbol,
		Summary:     buildSummary(detail, signals),
		Signals:     signals,
		Source:      "rule-based",
		GeneratedAt: now.UTC().Format("2006-01-02T15:04:05Z"),
	}, nil
}

func buildSignals(detail symbol.Detail, bars []market.Bar, sma []market.IndicatorPoint) []Signal {
	var signals []Signal

	// Momentum: today's change, straight from the quote.
	switch {
	case detail.ChangePercent > 0.1:
		signals = append(signals, Signal{
			Label:     "Momentum",
			Detail:    fmt.Sprintf("Up %.2f%% today", detail.ChangePercent),
			Direction: "bullish",
		})
	case detail.ChangePercent < -0.1:
		signals = append(signals, Signal{
			Label:     "Momentum",
			Detail:    fmt.Sprintf("Down %.2f%% today", -detail.ChangePercent),
			Direction: "bearish",
		})
	default:
		signals = append(signals, Signal{
			Label:     "Momentum",
			Detail:    "Roughly flat today",
			Direction: "neutral",
		})
	}

	// Trend: last close vs. the last SMA(20) value.
	if len(sma) > 0 && len(bars) > 0 {
		lastClose := bars[len(bars)-1].Close
		lastSMA := sma[len(sma)-1].Value
		diffPct := (lastClose - lastSMA) / lastSMA * 100
		switch {
		case diffPct > 1:
			signals = append(signals, Signal{
				Label:     "Trend",
				Detail:    fmt.Sprintf("%.1f%% above its 20-day average", diffPct),
				Direction: "bullish",
			})
		case diffPct < -1:
			signals = append(signals, Signal{
				Label:     "Trend",
				Detail:    fmt.Sprintf("%.1f%% below its 20-day average", -diffPct),
				Direction: "bearish",
			})
		default:
			signals = append(signals, Signal{
				Label:     "Trend",
				Detail:    "Trading close to its 20-day average",
				Direction: "neutral",
			})
		}
	}

	// Volume: latest bar vs. the trailing-20 average.
	if len(bars) >= smaPeriod {
		recent := bars[len(bars)-smaPeriod:]
		var sum int64
		for _, b := range recent {
			sum += b.Volume
		}
		avgVolume := float64(sum) / float64(len(recent))
		latestVolume := float64(bars[len(bars)-1].Volume)
		ratio := latestVolume / avgVolume
		switch {
		case ratio > 1.2:
			signals = append(signals, Signal{
				Label:     "Volume",
				Detail:    fmt.Sprintf("%.0f%% above its 20-day average", (ratio-1)*100),
				Direction: "bullish",
			})
		case ratio < 0.8:
			signals = append(signals, Signal{
				Label:     "Volume",
				Detail:    fmt.Sprintf("%.0f%% below its 20-day average", (1-ratio)*100),
				Direction: "bearish",
			})
		default:
			signals = append(signals, Signal{
				Label:     "Volume",
				Detail:    "In line with its 20-day average",
				Direction: "neutral",
			})
		}
	}

	return signals
}

func buildSummary(detail symbol.Detail, signals []Signal) string {
	bullish, bearish := 0, 0
	for _, sig := range signals {
		switch sig.Direction {
		case "bullish":
			bullish++
		case "bearish":
			bearish++
		}
	}

	var lean string
	switch {
	case bullish > bearish:
		lean = "leans constructive"
	case bearish > bullish:
		lean = "leans cautious"
	default:
		lean = "is mixed"
	}

	return fmt.Sprintf(
		"%s (%s, %s) %s on the signals below. This is a rule-based read of price, trend, and volume -- not financial advice, and not generated by a language model.",
		detail.Symbol.Symbol, detail.Exchange, detail.Sector, lean,
	)
}
